# Generated by Django 4.2.6 on 2023-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_student_emergency_contact_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(default='TBU', max_length=10),
        ),
    ]
